In [1]:
import numpy as np


1D Array

In [2]:
## Creation of array 1D array

arr = np.array([24,56,66,34,55,78,89])
arr

array([24, 56, 66, 34, 55, 78, 89])

In [3]:
type(arr)
# ndarray  ==> n Diminensional array

numpy.ndarray

In [4]:
arr.size # no. of items 

7

In [5]:
len(arr)

7

In [6]:
arr.ndim  # to check the diminension of an array

1

In [10]:
arr = np.array([24,56,66,34,55,78,89])
arr


array([24, 56, 66, 34, 55, 78, 89])

In [11]:
arr.dtype  # Check datatype of an array

dtype('int32')

In [15]:
arr = np.array([24,56,66,34,55,78,89 , 34.25])
arr

array([24.  , 56.  , 66.  , 34.  , 55.  , 78.  , 89.  , 34.25])

In [16]:
arr.dtype

dtype('float64')

In [19]:
arr = np.array([24,56,66,34,55,78,89 ,34.25,'upflairs',True])
arr

## similar type store
## similar type of array element/items


array(['24', '56', '66', '34', '55', '78', '89', '34.25', 'upflairs',
       'True'], dtype='<U32')

In [18]:
arr.dtype

dtype('<U32')

In [14]:
print(np.__version__) # for checking which  version is used 

1.26.4


In [25]:
arr = np.array([24,56,66,34,55,78,89])
arr[3]

34

In [27]:
arr[-2]

78

In [26]:
arr[2:4]

array([66, 34])

In [28]:
arr[2:]

array([66, 34, 55, 78, 89])

In [30]:
arr[-1] = 400
arr

array([ 24,  56,  66,  34,  55,  78, 400])

In [31]:
arr + 2 # addition 2 in all item in arr

array([ 26,  58,  68,  36,  57,  80, 402])

In [32]:
arr * 2

array([ 48, 112, 132,  68, 110, 156, 800])