2D Array

In [53]:
import numpy as np

In [54]:
ls = [[1,2,3],[3,2,5],[6,7,9]]
ls

[[1, 2, 3], [3, 2, 5], [6, 7, 9]]

In [55]:
type(ls)

list

In [56]:
ls[0]

[1, 2, 3]

In [57]:
ls[1]

[3, 2, 5]

In [58]:
arr = np.array(ls)
arr

array([[1, 2, 3],
       [3, 2, 5],
       [6, 7, 9]])

In [59]:
arr.ndim # for diminension of an array

2

In [60]:
arr.shape    # 5 row 3 column

(3, 3)

In [61]:
arr[2] # for single row

array([6, 7, 9])

In [62]:
arr[0:2]

array([[1, 2, 3],
       [3, 2, 5]])

In [63]:
arr[1,1:]

array([2, 5])

In [66]:
arr[-2:,-2:]

array([[2, 5],
       [7, 9]])

In [68]:
arr[-1:,-1:]

array([[9]])

In [69]:
arr[-1,-1] = 30
arr

array([[ 1,  2,  3],
       [ 3,  2,  5],
       [ 6,  7, 30]])

In [72]:
arr1 = np.random.randint(1,200,500) # it generate random array
arr1  # single diminension array 

array([162,  28,   7,  14, 106,  22, 147,  92,  92, 191, 163, 113,  69,
       129,  29,  76, 121,  74,  83, 116,  75, 108, 170,  13,  78, 111,
        66,  19, 172,   3,  66,  45, 148, 180,  74, 151, 146, 149, 172,
       154,  97, 129,  81,  42, 195,  18, 112,  16, 100,   4,  96, 101,
       183, 112,  74, 183, 111, 191,  13,  21,  16, 109,  58,  68, 160,
       123, 111, 123, 129, 160,  49, 154,  90, 163, 179, 139,  85, 139,
        65, 104,  98, 108,  66, 120,  41,  56, 151, 196,   1, 116,  34,
       147,  39, 125,   3, 135,  75,  54, 180,  96, 189,  65, 181, 126,
        84,  63, 130,   4,  20, 163, 117, 179,  35, 132,  28, 151, 180,
        92, 147,  61,  68,  63,  30, 180, 110, 145, 145,  92,  32,  12,
        60,  39,  82, 118,  77, 198, 185, 122,  57,  69, 119, 121,  97,
        30,  83, 193,  70, 119,  68,  27,  22, 169, 169,  62, 174,  18,
        49,  87,  62, 151,  73, 187,  55,  53,  67, 160, 125,   5, 154,
        79, 123, 125, 181, 107,  45,  99, 188,  61,  79, 149,  9

In [ ]:
# arr filter all those items that are less then equals to 100
# comments ----> how many items in your arrays 

In [75]:
arr1[arr1 <= 100]


array([ 28,   7,  14,  22,  92,  92,  69,  29,  76,  74,  83,  75,  13,
        78,  66,  19,   3,  66,  45,  74,  97,  81,  42,  18,  16, 100,
         4,  96,  74,  13,  21,  16,  58,  68,  49,  90,  85,  65,  98,
        66,  41,  56,   1,  34,  39,   3,  75,  54,  96,  65,  84,  63,
         4,  20,  35,  28,  92,  61,  68,  63,  30,  92,  32,  12,  60,
        39,  82,  77,  57,  69,  97,  30,  83,  70,  68,  27,  22,  62,
        18,  49,  87,  62,  73,  55,  53,  67,   5,  79,  45,  99,  61,
        79,  92,  88,  95,  46,  49,  26,  38,  44,  41,  85,  90,  60,
        11,  40,  56, 100,  48,  15,  87,  33,  49,  82,   3,  86,  33,
        31,  71,  27,  57,  25,   2,  10,  37,  60,  28,  71,  69,  17,
        48,  76,  87,  27,  50,  91,  22,  29,  43,  75,  48,  22,  50,
        59,  42,  45,  15,  45,  54,  51,  83,  83, 100,  15,  48,  49,
        97,  43,  76,  84,  94,  66,  55,  93,  57,  12,  98,  13,  36,
        36,  61,  81,  31,   3,  66,  81,  20,   7,  46,  28,  8

In [76]:
arr1[arr1 <= 100].size

264

In [79]:
len(arr1 <= 100)

500

In [80]:
arr1[arr1 <= 100].shape

(264,)

In [81]:
arr2 = np.random.randint(1,200,(10,5))
arr2

array([[149, 104,  38,  83, 126],
       [177,  89,  26, 101,  39],
       [100, 179, 160, 113, 188],
       [114, 186, 111, 168,  20],
       [151,  43,  23,  62, 181],
       [ 98,  69, 156,  44, 123],
       [ 12, 136, 129,  82,  33],
       [119, 176, 189,  56, 197],
       [155,   4, 122, 185,  93],
       [126,  24, 146,  72,  70]])

In [82]:
arr2.ndim

2

In [83]:
arr3 = np.zeros(10)
arr3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [88]:
arr3.ndim

2

In [85]:
arr3.dtype

dtype('float64')

In [86]:
arr3 = np.zeros((10,5))
arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [87]:
arr3.ndim

2

In [89]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [90]:
arr = np.ones((10,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [91]:
ls = [0,1,2,3,4,5,6,7,8,9]
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [92]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [94]:
ls = list(range(10))
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [95]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
arr = np.arange(5,30)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [99]:
arr = np.arange(60)
arr  # 1D single

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [100]:
arr.reshape(10,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [106]:
arr = arr.reshape(6,10)

In [105]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [104]:
arr.reshape(20,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])