In [1]:
import numpy as np

In [26]:
ls = [[[1,2,3],[3,4,6],[45,67,56]],[[3,2,5],[6,7,9],[56,88,9]]]
ls

[[[1, 2, 3], [3, 4, 6], [45, 67, 56]], [[3, 2, 5], [6, 7, 9], [56, 88, 9]]]

In [27]:
type(ls)

list

In [28]:
arr = np.array(ls)
arr

array([[[ 1,  2,  3],
        [ 3,  4,  6],
        [45, 67, 56]],

       [[ 3,  2,  5],
        [ 6,  7,  9],
        [56, 88,  9]]])

In [29]:
arr.ndim # for diminension of an array

3

In [30]:
arr.shape   

(2, 3, 3)

In [4]:
arr = np.random.randint(1,200,(3,5,3))
arr

array([[[ 57, 191, 196],
        [179, 137, 117],
        [157, 152, 171],
        [  5, 182, 126],
        [  1,  63, 134]],

       [[ 97,  44,  34],
        [ 48,  61, 183],
        [ 40,  10, 150],
        [ 65, 115,  16],
        [118, 178, 119]],

       [[154, 100, 133],
        [  1, 104, 130],
        [123, 118, 180],
        [172, 159,  70],
        [177,  17,  91]]])

In [5]:
arr.shape

(3, 5, 3)

In [12]:
arr.ndim

3

In [6]:
# arr[table,row,column]
arr[1,4,0:]

array([118, 178, 119])

In [7]:
arr[2,0:2,1:]

array([[100, 133],
       [104, 130]])

In [8]:
arr[0:,0]

array([[ 57, 191, 196],
       [ 97,  44,  34],
       [154, 100, 133]])

In [10]:
arr[-3:,-5]

array([[ 57, 191, 196],
       [ 97,  44,  34],
       [154, 100, 133]])

In [13]:
arr[0:,0]

array([[ 57, 191, 196],
       [ 97,  44,  34],
       [154, 100, 133]])

# Functions in array

In [14]:
arr = np.array([9,7,8])
arr

array([9, 7, 8])

In [15]:
max(arr)

9

In [16]:
min(arr)

7

In [17]:
np.mean(arr)  # average 

8.0

In [18]:
np.sum(arr)

24

In [19]:
np.argmin(arr)  # it will return index of minimum item 

1

In [20]:
np.argmax(arr)  # it will return index of maximum item

0

In [22]:
arr.sort()  # ascending order
arr

array([7, 8, 9])

In [23]:
arr[::-1]   # for reverse sorting or desending order

array([9, 8, 7])